name: Lint, then Test

on:
  pull_request:
    branches: [master]
    types: [opened, ready_for_review, reopened, synchronize, unlocked]
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile --silent

      - name: Check for Prettier errors
        run: yarn pretty
        continue-on-error: true

      - name: Lint JS
        run: yarn lint.js

      - name: Lint Stylesheets
        run: yarn lint.style

  cypress-run:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      # checkout acstb.name repo
      - name: Checkout
        uses: actions/checkout@v2

      # run tests with Cyrpess's github action.
      #
      # For the sake of safety, the version **must be explicitly specified.**
      #
      # Without an explicit version, you run the risk of running insecure code.
      #
      # If someone else gains access to the account which publishes this GitHub
      # Action, and pushes a new minor version which (for example) steals your
      # code, then e.g. "@v2" will go from "v2.0.7" to "v2.0.8" without any
      # trouble.
      #
      # To avoid this, use an explicitly specified version tag: e.g. "@v2.0.7".
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          record: true
          group: merge
          tag: ${{ github.event_name }}
          install-command: yarn --frozen-lockfile --silent
          start: yarn run dev
          wait-on: "http://localhost:3000"
          browser: chrome
        # Pass the github_token explicitly, so that Cypress can use it to
        # identify the run.
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
