name: Lint, then Test

on:
  pull_request:
    branches: [master]
    types: [opened, ready_for_review, reopened, synchronize, unlocked]
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile --silent

      - name: Check for Prettier errors
        run: yarn pretty
        continue-on-error: true

      - name: Lint JS
        run: yarn lint.js

      - name: Lint Stylesheets
        run: yarn lint.style
