# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and Test

on:
  pull_request:
    branches: [master]
    types: [opened, ready_for_review, reopened, synchronize, unlocked]
  push:
    branches: [master]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Check for Prettier errors
        run: yarn pretty
        continue-on-error: true

      - name: Lint JavaScript
        run: yarn lint.js

      - name: Lint Stylesheets
        run: yarn lint.style
